CREATE USER 'tuan'@'%' IDENTIFIED BY 'tuan';

GRANT CREATE, CREATE USER, SELECT, RELOAD  ON *.* TO 'tuan'@'%';

GRANT EXECUTE, SELECT, SHOW VIEW, ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, INDEX, INSERT, REFERENCES, TRIGGER, UPDATE, LOCK TABLES  ON user_registration.* TO 'tuan'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;

